SELECT COUNT(*) FROM Data WHERE A > 10 AND B < 20;
SELECT COUNT(*) FROM Data WHERE A < 20 AND B > 30;
SELECT COUNT(*) FROM Data WHERE B > 10 AND C < 20;
SELECT COUNT(*) FROM Data WHERE B > 10 AND A < 50;
SELECT COUNT(*) FROM Data WHERE C > 50 AND B < 20;
SELECT COUNT(*) FROM Data WHERE A > 20 AND C < 60;
SELECT COUNT(*) FROM Data WHERE A > 90 AND C < 20;
SELECT COUNT(*) FROM Data WHERE A > 50 AND B < 20;
SELECT COUNT(*) FROM Data WHERE A < 10 AND B > 70;
SELECT COUNT(*) FROM Data WHERE A < 30 AND B < 10;

